# Generated by Django 4.2.7 on 2023-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('ocean', 'Ocean Freight'), ('air', 'Air Freight'), ('rail', 'Rail Freight'), ('warehousing', 'Warehousing'), ('customs', 'Customs Clearance'), ('distribution', 'Distribution')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
