# Generated by Django 4.2.7 on 2023-11-08 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logisticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='forwarded_to',
            field=models.ManyToManyField(blank=True, related_name='forwarded_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
