# Generated by Django 4.2.7 on 2023-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0003_quote_is_forwarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
    ]
