# Generated by Django 4.2.7 on 2023-11-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
