# Generated by Django 4.2.7 on 2023-11-08 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logisticapp', '0006_contact_forwarded_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='forwarded_to',
        ),
        migrations.AddField(
            model_name='contact',
            name='forwarded_to',
            field=models.ManyToManyField(blank=True, related_name='contacts_forwarded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
